### ISSUE TITLE
Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean

### ISSUE THREAD

**Issue by tarakranjan** [solita/clamav-rest#9]
</licenses>
 :: Spring Boot ::        (v1.4.0.RELEASE)

2016-09-16 20:20:06.047  INFO 5243 --- [           main] fi.solita.clamav.Application             : Starting Application v1.0.1 on vagrant-ubuntu-trusty-64 with PID 5243 (/vagrant/target/clamav-rest-1.0.1.jar started by vagrant in /vagrant/target)
2016-09-16 20:20:06.070  INFO 5243 --- [           main] fi.solita.clamav.Application             : No active profile set, falling back to default profiles: default
2016-09-16 20:20:06.337  INFO 5243 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3267b4ba: startup date [Fri Sep 16 20:20:06 UTC 2016]; root of context hierarchy
2016-09-16 20:20:10.278  WARN 5243 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
2016-09-16 20:20:10.351 ERROR 5243 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.context.ApplicationContextException: Unable to start embedded container; nested exception is org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:137) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:535) ~[spring-context-4.3.2.RELEASE.jar!/:4.
�
    </license>
3.2.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:369) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at fi.solita.clamav.Application.main(Application.java:38) [classes!/:1.0.1]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.7.0_111]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57) ~[na:1.7.0_111]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_111]
	at java.lang.reflect.Method.invoke(Method.java:606) ~[na:1.7.0_111]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [clamav-rest-1.0.1.jar:1.0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [clamav-rest-1.0.1.jar:1.0.1]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [clamav-rest-1.0.1.jar:1.0.1]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:58) [clamav-rest-1.0.1.jar:1.0.1]
Caused by: org.springframework.context.ApplicationContextException: Unable to start EmbeddedWebApplicationContext due to missing EmbeddedServletContainerFactory bean.
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.getEmbeddedServletContainerFactory(EmbeddedWebApplicationContext.java:189) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.createEmbeddedServletContainer(EmbeddedWebApplicationContext.java:162) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.onRefresh(EmbeddedWebApplicationContext.java:134) ~[spring-boot-1.4.0.RELEASE.jar!/:1.4.0.RELEASE]
	... 14 common frames omitted

**Comment by lokori** [comment]
Could you provide more information how this happens? No one else has reported this and I haven't been able to reproduce this either locally or with Docker version.

**Comment by iweisband** [comment]
I had this Exception in the following situation.

in my POM was properties:

<properties>
    <java.version>1.8</java.version>
    
    <start-class>com.scmaer.java.microservice.Application</start-class>
    <cxf.version>3.1.5</cxf.version>
    <olingo.version>2.0.10</olingo.version>
    <spring.boot.version>1.4.7.RELEASE</spring.boot.version>
    <spring.boot.plugin.version>1.5.8.RELEASE</spring.boot.plugin.version>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <skipTests>false</skipTests>
</properties>
and the name and path of my application class ("start-class") was wrong.
